### ISSUE TITLE
Rotate Credentials in CircleCI

### ISSUE THREAD

**Issue by akhon** [verygoodsecurity/LittleProxy#14]
> CircleCI engineers identified a bug late Friday evening that leaked environment variables in open-source projects that allow building forked pull requests. Your project *https://circleci.com/gh/verygoodsecurity/LittleProxy* is one of those affected.
> An engineer patched the issue and it is already in production so this should not be an issue going forward. There is no evidence of lost data or known malicious behavior as a result of the issue.
> However, we recommend you rotate any sensitive credentials stored as environment variables in those projects.

Someone with access to project configuration should do that

**Comment by mjallday** [comment]
this has been done. these credentials are shared across lp, vault and acceptance project.
